# The overall Google Cloud Project ID.  This property is mandatory
# I case the GCP project name is different from the ID, make sure ID is used here.
PROJECT_ID: keep-ahope

# --------------------------------------------------------------------------------------
# It is assumed that the CloudSQL instance we use to store data is in the same project
# and therefore no need to create a service account to access across project.
# --------------------------------------------------------------------------------------

# CLOUDSQL_REGION identifies the geographical region of the CloudSQL instance.
# This is selected at the time of instance creation.
CLOUDSQL_REGION: us-east1

# CLOUDSQL_INSTANCE_ID identifies an instance of Google Cloud SQL, which should be viewable at
# https://console.cloud.google.com/sql/instances.  The left-most column is the instance id.
CLOUDSQL_INSTANCE_ID: ahope-postgres-dev

# CLOUDSQL_CONNECTION_NAME:
# An instance's connection name can be viewed in the Overview tab of the "Instance details" page.
# It is concatenation of $PROJECT_ID:$CLOUDSQL_REGION:$CLOUDSQL_INSTANCE_ID, separated by colons.
# If this property is not defined in this yml file, then it will be formed by concatenating the
# three properties defined above.
# If this property is defined, then no need to define CLOUDSQL_INSTANCE_ID, and CLOUDSQL_REGION.
# CLOUDSQL_CONNECTION_NAME: keep-ahope:us-east1:ahope-postgres-dev

# DATABASE_CREDENTIALS is the CloudSQL database user and the password, separated by a colon.
# This property is mandatory unless DATABASE_URI is defined (which includes it)
DATABASE_CREDENTIALS: postgres:ki0YfYUzZHOQ5l4v

# DATABASE_NAME is the name of the database inside a CloudSQL instance.  A CloudSQL instance is just an instance
# of PostgreSQL server, which is capable of hosting multiple databases inside it, and hence a database name
# is needed to identify the database to use.
# This property is mandatory unless DATABASE_URI is defined (which includes it)
DATABASE_NAME: ahope

# DATABASE_URI, when undefined here, is formed as 
#   postgres://$DATABASE_CREDENTIALS@/cloudsql/$CLOUDSQL_CONNECTION_NAME/$DATABASE_NAME
# DATABASE_URI: postgres://postgres:ki0YfYUzZHOQ5l4v@/cloudsql/keep-ahope:us-east1:ahope-postgres-dev/ahope

# DATABASE_OPTIONS, leave it undefined for Cloud environment.
#DATABASE_OPTIONS:
#  protocol: "socket:"
#  host: /cloudsql/keep-ahope:us-east1:ahope-postgres-dev:ahope
#  database: ahope

# If no MASTER_KEY is configured, then a randomly generated one will be used.  This is recommended.
# MASTER_KEY: ahope-test-app-master-key-keep-it-secret

# Note: FILE_KEY is only needed if we store files.
# FILE_KEY: <your-file-key>,

# PARSE_MOUNT_PATH: /parse

# SERVER_URL: https://ahope-parse-poc.appspot.com/parse

# Get the OAuth Client ID here:
# https://console.cloud.google.com/apis/credentials?project=keep-ahope&orgonly=true&supportedpurview=organizationId
#
OAUTH_CLIENT_ID: 888227269181-14qpprrki7r8l9b6gaknd9fle8gkas9k.apps.googleusercontent.com

# Whether to allow a client to create classes (custom tables).  Default to false, but can be changed to true during development
# ALLOW_CLIENT_CLASS_CREATION: false

DASHBOARD_SETTINGS:
  # If a different Parse server is used, then uncomment the following section.
  # apps:
  #   - serverUrl: https://an_alternative_parse_server/parse
  users:
    - user: ahope-admin
      pass: $2y$12$ssWRVAqcxuumoLZGlaCI1O8NRo36II43VRuiiEaqFIqNjttDGaCiG
  useEncryptedPasswords: true
